# Generated by Django 4.1.2 on 2023-06-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=100)),
                ('study', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('hour', models.TimeField()),
            ],
        ),
    ]
