# Generated by Django 4.1.2 on 2023-06-07 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_rename_states_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=4)),
            ],
        ),
        migrations.RemoveField(
            model_name='state',
            name='name',
        ),
        migrations.AddField(
            model_name='state',
            name='contraction',
            field=models.CharField(default='HOLA', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='state',
            name='state',
            field=models.CharField(default='HOPLA', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='state',
            name='code',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='town',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.state'),
        ),
    ]
