# Generated by Django 4.1.2 on 2023-06-08 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_town_remove_state_name_state_contraction_state_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='study',
            name='code',
            field=models.CharField(default=9, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.study'),
        ),
    ]
