# Generated by Django 4.1.2 on 2023-06-08 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_study_code_alter_appointment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='user_id',
            field=models.EmailField(default=11, max_length=254),
            preserve_default=False,
        ),
    ]
